version: 2

jobs:

  build:
    docker:
      - image: circleci/node:11
    steps:
      - run: wget https://github.com/ethereum/solidity/releases/download/v0.5.9/solc-static-linux && chmod +x solc-static-linux && sudo mv solc-static-linux /usr/bin/solc
      - run: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - checkout
      - run: npm i
      - run: npm test

  publish_npm:
    docker:
      - image: circleci/node:11
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - checkout
      - run: npm publish

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /.*/
      - publish_npm:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
